@startuml
title Диаграмма состояний
top to bottom direction
hide empty description
skinparam nodesep 65

[*] --> МероприятияОтображены
МероприятияОтображены --> Поиск : Выбор фильтров и поиск
Поиск --> МероприятияОтображены
МероприятияОтображены --> Сортировка : Выбор сортировки
Сортировка --> МероприятияОтображены

МероприятияОтображены --> ДеталиМероприятия : Выбор мероприятия
ДеталиМероприятия --> Авторизация : Нажать "Купить билеты" / Анонимный пользователь
Авторизация --> Авторизация : Неуспешная авторизация
Авторизация --> ДеталиМероприятия : Нажать "Назад"
Авторизация --> ОформлениеЗаказа : Успешная авторизация
ДеталиМероприятия --> ОформлениеЗаказа : Нажать "Купить билеты" / Посетитель

ОформлениеЗаказа --> СхемаЗала : Просмотр мест

СхемаЗала --> Резервирование : Переход к резервированию / Доступно резервирование
СхемаЗала --> Оплата : Переход к оплате

Резервирование --> Оплата : Предоплата/Полная оплата
Резервирование --> ЗаказОформлен : Зарезервировать / Предоплата необязательна
Резервирование --> [*] : Отменить резервирование

ЗаказОформлен --> ЗаказОтменен : Отменить заказ / Без оплаты
ЗаказОформлен --> Оплата : Оплатить заказ 
ЗаказОформлен --> ЗаказОтменен : Вышел срок для оплаты
ЗаказОформлен --> Заказы : Переход в заказы

Оплата --> ЗаказОплачен : Успешная оплата
Оплата --> ЗаказОформлен : Успешная оплата
Оплата --> [*] : Ошибка оплаты 

ЗаказОплачен --> БилетыСкачаны : Скачать билеты
ЗаказОплачен --> Заказы : Переход в заказы
БилетыСкачаны --> Заказы : Переход в заказы
Заказы --> [*]

Заказы --> ДеталиЗаказа : Посмотреть заказ
ДеталиЗаказа --> ОтзывОтправлен: Оставить отзыв / После завершения мероприятия
ОтзывОтправлен --> [*]

ЗаказОформлен --> [*]
ЗаказОплачен --> [*]
ЗаказОтменен --> [*]
БилетыСкачаны --> [*]
@enduml